### ISSUE TITLE
Add chapter Binary Search

### ISSUE THREAD

**Issue by TunchinKao** [NTHU-CP/NTHU-CPP#11]
- Basic of Binary Search
- Recursive Binary Search
- Iterative Binary Search
- close/open interval
- Binary Search on Answer
- Problem set

**Comment by harry900831** [comment]
maybe introduce std::lower_bound and std::upper_bound at last?

**Comment by harry900831** [comment]
@TunchinKao Do you still have a plan on adding this topic?

**Comment by TunchinKao** [comment]
@harry900831  No, sorry.
