### ISSUE TITLE
Add chapter disjoint set

### ISSUE THREAD

**Issue by JstMonika** [NTHU-CP/NTHU-CPP#16]
- Definition of set, disjoint set
- Naive find, union
- Time complexity of naive disjoint set
- Path compression and union by rank
- Optimized time complexity
- Template of disjoint set with explanation
- Problem set

**Comment by harry900831** [comment]
@JstMonika Do you still have a plan on adding this topic?

**Comment by JstMonika** [comment]
Probably not. Thanks.
