### ISSUE TITLE
Add chapter Bit operation and their trick

### ISSUE THREAD

**Issue by fffelix-huang** [NTHU-CP/NTHU-CPP#21]
- Introduction to bit and bytes
- Basic bit operation / truth table
- Some trick for using bit operation
- Eight queen
- Bit representation / bitmask
- Enumerate all subset and submask

**Comment by harry900831** [comment]
I would prefer pull eight queen out to an individual topic.

**Comment by harry900831** [comment]
@fffelix-huang Do you still have a plan on adding this topic?

**Comment by harry900831** [comment]
ping @fffelix-huang

**Comment by fffelix-huang** [comment]
我暑假會補完 QQ
