### ISSUE TITLE
Add Rolling Hash

### ISSUE THREAD

**Issue by lawrence910426** [NTHU-CP/NTHU-CPP#33]
Outlines are as the following comments

**Comment by lawrence910426** [comment]
# Introduction to polynomial hash
- How to calculate rolling hash
- Check if strings are identical
- Mathematical analysis of the collision rate
- Compare the string lexicographically (by binary search)
- A simple introduction of how to pick the right modulo and base (General case)
- Basic hash problems
    - Get the hash value of a substring
    - Alternative solution of KMP, Manacher
    - For normal competitive programmers

**Comment by lawrence910426** [comment]
# Hacking Rolling Hash
- Thue-Morse construction for for modulo like 2^N
- Birthday-Paradox could be used for most scenarios
- Tree-Method generates long strings and is faster than birthday-paradox
- Lattice-Method could be used for big alphabets (like English letters)
- Composition-Method could be used for multiple vulnerable hashes
- Pick modulo and base

No example problem needed. But providing a template hacking function would be nice.

**Comment by lawrence910426** [comment]
# Advanced Rolling Hash Problems
1. [ ] Finding the lexicographically minimal cyclic shift of a string of length n in O(n log n) time
2. [ ] Sorting of all cyclic shifts of a string of length n in lexicographic order in O(n log^2 n) time
3. [ ] Finding the number of sub-palindromes of a string of length n in O(n log n) time
4. [ ] Largest common prefix of two strings length n with swapping two chars in one of them in O(n log n) time
5. [ ] The number of suffixes of a string of length n, the infinite extension of which coincides with the infinite extension of the given string for O(n log n) (extension is a duplicate string an infinite number of times)

**Comment by lawrence910426** [comment]
# Appendix
Does Rolling Hash of (S[0],x^0) and (S[-1], x^0) differ from each other?

**Comment by harry900831** [comment]
@lawrence910426 Missing references

**Comment by lawrence910426** [comment]
References:
- [blog](https://codeforces.com/blog/entry/60442)
- [blog](https://codeforces.com/blog/entry/100027)
- [Slides](https://docs.google.com/presentation/d/1Z2AkqOqP85WLxSyPRUj9Inw8elXp8LHXCbrdn0MfCx8/edit?usp=sharing)
