### ISSUE TITLE
Add LCA

### ISSUE THREAD

**Issue by didwhddks** [NTHU-CP/NTHU-CPP#39]
# Outline
- Definition of lowest common ancestor (LCA)
- Common implementations for finding LCA
  - Brute force
  - Binary lifting
  - Reduce to RMQ problem with Euler tour
    - How to reduce to RMQ problem
    - Some useful methods on solving RMQ (mentioned)
    - Farach-Colton and bender algorithm (detailed)
  - Tarjan's offline algorithm
  - Heavy path decomposition
  - Some related problems
    - [CSES - Company Queries II](https://cses.fi/problemset/task/1688)
    - [SPOJ - Query on a tree II](https://www.spoj.com/problems/QTREE2/)
- Reduction from RMQ problem to LCA problem with Cartesian tree
- Summary
# References
- <https://web.ntnu.edu.tw/~algo/Tree2.html>
- <https://oi-wiki.org/graph/lca/>
- <https://cp-algorithms.com/graph/lca.html>
- <https://cp-algorithms.com/graph/lca_binary_lifting.html>
- <https://cp-algorithms.com/graph/lca_farachcoltonbender.html>
- <https://cp-algorithms.com/graph/lca_tarjan.html>
- <https://codeforces.com/blog/entry/43917>
- <https://www.topcoder.com/thrive/articles/Range%20Minimum%20Query%20and%20Lowest%20Common%20Ancestor>
- <https://oi-wiki.org/topic/rmq/>
- <https://oi-wiki.org/ds/cartesian-tree/>

**Comment by didwhddks** [comment]
@harry900831 Hi, I updated something in my outline.

**Comment by didwhddks** [comment]
Is there anything that needs to be added or changed in the outline?
I noticed that I haven't been assigned this issue yet.

**Comment by harry900831** [comment]
So far so good, we may discuss further after you provide the draft. Thanks.
