### ISSUE TITLE
Add Convex Hull Trick

### ISSUE THREAD

**Issue by aftermaaath** [NTHU-CP/NTHU-CPP#42]
#### 斜率/查詢皆單調
說明斜率優化觀念、使用 deque
- 點不用被 pop
- 點需要被 pop

#### 查詢不單調、斜率單調
使用二分搜

#### 斜率不單調
- 李超線段樹
- 動態凸包
- CDQ

/\*
以上每個部分都有：
- 例題
- 提出觀察、列出&整理轉移式
- 時間複雜度、實作細節
- 範例 code
- 總結作法與重點

\*/

#### 總結
- 統整各情況、列出思考的步驟

### Exercises
- 簡述題目、題解
- https://codeforces.com/contest/1083/problem/E
- https://codeforces.com/contest/311/problem/B
- https://codeforces.com/problemset/problem/319/C
- https://cses.fi/problemset/task/2087
  https://cses.fi/problemset/task/2084
- https://tioj.ck.tp.edu.tw/problems/1676
- https://tioj.ck.tp.edu.tw/problems/1745
- https://codeforces.com/contest/932/problem/F
- https://cses.fi/problemset/task/2085
- https://tioj.ck.tp.edu.tw/problems/1921
  
### References
- [Oi wiki - 斜率優化](https://oi-wiki.org/dp/opt/slope/)
- [TIOJ 建中培訓講義](https://tioj.ck.tp.edu.tw/uploads/attachment/5/27/5.pdf)
- [Algorithms for competetive programming - Convex hull trick](https://cp-algorithms.com/geometry/convex_hull_trick.html)
- [[Tutorial] Convex Hull Trick — Geometry being useful](https://codeforces.com/blog/entry/63823)
- [PEGWiki - Convex hull trick](https://wcipeg.com/wiki/Convex_hull_trick)
- [USACO Guide - Convex Hull Trick](https://usaco.guide/plat/convex-hull-trick?lang=cpp)
- https://www.cnblogs.com/Xing-Ling/p/11210179.html

**Comment by harry900831** [comment]
A problem that may related to this topic: https://onlinejudge.org/index.php?option=onlinejudge&Itemid=8&page=show_problem&problem=3547. It's ICPC World Finals 2011 problem.
