### ISSUE TITLE
Add Suffix Array

### ISSUE THREAD

**Issue by bear1222** [NTHU-CP/NTHU-CPP#48]
### Implementation
- 倍增法
- SA-IS
### Reference
- https://cp-algorithms.com/string/suffix-array.html
- https://oi-wiki.org/string/sa/

**Comment by harry900831** [comment]
Are you still planning on adding this topic?

**Comment by bear1222** [comment]
No, sorry…

Harry Chiang ***@***.***>於 2023年6月27日 週二，下午8:45寫道：
